name: responsePlotting
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib=3.3
  - bokeh=2.3
  - ipywidgets
#widgetsnbextension-3?
  - notebook=6.2
  - numpy=1.20
#  - openpyxl
  - pandas=1.2
  - pip=21
  - scipy=1.6
  - seaborn=0.11
  - mplhep 0.2.18
#  - pip
#  - xlrd
#  - lxml
#  - cryptography
#  - simplegeneric
#  - cython
#  - geopandas
